# Generated by Django 4.2.5 on 2023-09-20 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='location',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.CharField(default=datetime.datetime(2023, 9, 20, 11, 51, 45, 88294, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
